### ISSUE TITLE
Irmin FS store on mirage

### ISSUE THREAD

**Issue by SahanaKrishnaKarki** [mirage/irmin#1019]
I am trying to build a irmin FS store on mirage OS.

module Store = Irmin_unix.Git.FS.KV(Irmin.Contents.String)
    
      (* Database configuration *)
      let config = Irmin_git.config ~bare:true "/tmp/irmin/test" 

      (* Commit author *)
      let author = "xyz <xyz@example.com>" 

      (* Commit information *)
      let info fmt = Irmin_unix.info ~author fmt 

But I am getting the below error.
```

Error: No implementations provided for the following modules:
Checkseum referenced from /home/sahana/.opam/4.06.0/lib/decompress/impl/impl.cmxa(Impl__Decompress_safe),
/home/sahana/.opam/4.06.0/lib/decompress/impl/impl.cmxa(Impl__Decompress_window),
/home/sahana/.opam/4.06.0/lib/decompress/impl/impl.cmxa(Impl__Decompress_inflate),
/home/sahana/.opam/4.06.0/lib/decompress/impl/impl.cmxa(Impl__Decompress_deflate),
/home/sahana/.opam/4.06.0/lib/git/git.cmxa(Git__Crc32)
Digestif referenced from /home/sahana/.opam/4.06.0/lib/git/git.cmxa(Git__Mem),
/home/sahana/.opam/4.06.0/lib/git-unix/git_unix.cmxa(Git_unix),
/home/sahana/.opam/4.06.0/lib/irmin/irmin.cmxa(Irmin__Hash)
Command exited with code 2.
```

Should I pass the file as a device or something? Not sure what the error means.

**Comment by dinosaure** [comment]
The error is due to a use of `virtual_modules` by `checkseum` (and `digestif`). The `mirage` tool does not know the default implementation of it and it can not select the right `*.cmx`) (note that this error is fixed with `dune` but MirageOS 3 does not yet use `dune`).

To fix it, you must choose which implementation you want and put a `_tags` file (needed by `ocamlbuild`) such as [unipi](https://github.com/roburio/unipi/blob/master/_tags#L1) or some others unikernels.

In the example, we choose the C implementation (eg. `checkseum.c` and `digestif.c`) which is fast but you can use the OCaml implementation if you want.

**Comment by samoht** [comment]
How do you compile your example? If you are using `dune` it should pick a default implementation for you.

**Comment by SahanaKrishnaKarki** [comment]
I am using the below commands:

mirage configure -t unix
make
./file

**Comment by SahanaKrishnaKarki** [comment]
Thanks @dinosaure . It worked.
