### ISSUE TITLE
Inode.v is inefficient

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1272]
Currently, creating a new inodes from a set of bindings is done by incrementatly adding these bindings to the empty inode. This is super inefficient as it allocates a lot of intermediate arrays for no good reason. This happens for instance when we try to export a large directory during a commit.

We should be able to create an inode tree from a list of bindings directly.

**Comment by Ngoguey42** [comment]
I tracked down the problem using #1269's collapse mode. We indeed spend a lot of time in `Inode.v`, but the inode code is fine!

We are not allocating intermediate arrays in `Inode.v`, because your code already optimised that aspect thanks to the `~copy:false` parameter [here](https://github.com/mirage/irmin/blob/766b88128d5100762beaa10a7668c6d25773fb94/src/irmin-pack/inode.ml#L596).

There are still a lot of avoidable intermediate allocations in `Inode.v` though, but they don't seem to matter much. I tried, for example, to reduce to a minimum the number of `StepMap.t` constructions, but it led to no significant speedups.

---

After a long investigation I got to the following conclusion: it all comes from the poor implementation of `Tree.remove`.

Here is the recipe for disaster when running `bench/tree.exe` with `--collapse`:
- In the bootrap trace we remove one entry of `data/commitments`, a massive directory.
- [Tree.Node.remove](https://github.com/mirage/irmin/blob/766b88128d5100762beaa10a7668c6d25773fb94/src/irmin/tree.ml#L823) loads the full directory in memory to a `Node.Map`, a massive StepMap.
- In the bootstrap trace we execute a commit.
- During the `Tree.export` we have to recompute the hash of that directory [here](https://github.com/mirage/irmin/blob/766b88128d5100762beaa10a7668c6d25773fb94/src/irmin/tree.ml#L1222).
- To do so we convert that `Node.Map` back to an inode using `Node.v` [here](https://github.com/mirage/irmin/blob/766b88128d5100762beaa10a7668c6d25773fb94/src/irmin/tree.ml#L492), the full massive directory.

Those situations reprent ~90% of the time spent in `Node.v` during the commits.

We fix `Tree.remove`, we fix this issue :)

**Comment by samoht** [comment]
Interesting! I'm still a bit surprised that incrementally adding values one by one is ok. It's good to have benchmarks to test this assumption :-)

Removes also completely kills the usefulness of the tree cache, so we indeed need to do something about it.
