### ISSUE TITLE
Not clear how to build irmin

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1498]
I followed the suggested steps to build the development version:

```
git clone https://github.com/mirage/irmin
cd irmin/
opam install .
```

The log is here: https://gist.github.com/tomjridge/79c97efc455860de8d8c649600a02cd9

Typical error is: 

```
# (cd _build/default && .ppx/a780cbe06de92f0714dba2aa443899e8/ppx.exe --lib Type --cookie 'library-name="irmin"' -o src/irmin/info.pp.ml --impl src/irmin/info.ml -corrected-suffix .ppx-corrected -diff-cmd - -dump-ast)
# File "src/irmin/info.ml", line 24, characters 21-26:
# 24 |   [@@deriving irmin ~equal]
#                           ^^^^^
# Error: Ppxlib.Deriving: generator 'irmin' doesn't accept argument 'equal'
         ppx src/irmin/tree.pp.ml (exit 1)
```

So, some version mismatch with "deriving irmin". I noted the pin-depends stuff, and tried various alternative approaches but couldn't get anything to work (eventually hitting a "too many open files" error in ld, despite upping the limits to a huge number).

The OCaml-CI seems happy though, at least for Ubuntu (my environment): https://ci.ocamllabs.io/github/mirage/irmin/commit/b9849102b73a8036eb85e7bb7136bb35dbabf518

Help!

Thanks

**Comment by zshipko** [comment]
That error seems to come from having the latest release of `ppx_repr` installed rather than the development version. This whole setup can get tricky sometimes because of the way `irmin`, `repr` and `index` are  developed together but live in separate repos.

Other people have different workflows, but when I build irmin for development I do something like this (after cloning and switching into the irmin repo):

```
opam install . --deps-only --with-test   # install dependencies
dune build                               # build
dune runtest                             # run all tests 
```

During `opam install` you can install the pinned version of `repr`/`ppx_repr` and `index` - irmin master will typically require the latest commit of each of those to be installed. 

Or, if you're making lots of changes to `irmin` and `repr` or `index` you can use a "monorepo" workflow and clone the `repr` and `index` repos directly to the root of the irmin repo and `dune build` will automatically pick up the packages contained by those directories - you won't need to worry about installing them at all, but you will need to make sure they're up to date yourself.

Most of the time I don't worry about installing the irmin packages unless I'm building a library that depends on irmin being installed, but when I do I will pin each irmin library I need individually (or use a script to install all of them):
```
opam pin add ppx_irmin.dev /path/to/irmin --working-dir
opam pin add irmin.dev /path/to/irmin --working-dir
opam pin add irmin-pack.dev /path/to/irmin --working-dir
...
```
Hopefully that helps and doesn't just make things even more confusing!

**Comment by CraigFe** [comment]
Some things to note in addition to what @zshipko has said:

- Not using `--deps-only` when installing development dependencies will lead to odd results (especially for internal dependencies of multi-package repositories), since `opam` will attempt to install the opam-released versions of packages that already exist inside the repository. This is probably what's going wrong with the trace you've linked: Opam shouldn't be attempting to compile Irmin as part of installing the dependencies of Irmin. (The lack of `--with-test` and `--with-doc` flags is also problematic.)

- Irmin currently uses a Git submodule (to source [`tezos-context-hash`](https://github.com/tarides/tezos-context-hash/)), so you'll need to `git clone --recursive` to get the full set of development dependencies. Something like `git submodule pull --init` should work  to re-hydrate the submodules of an existing clone.

- Because of the way that Dune projects are composable (i.e. injecting the source tree of a project X into a project Y makes the dependency X available to Y), there's no single `opam` command (that I'm aware of) that installs all of the dependencies of a Dune project. OCaml-CI uses the moral equivalent of `opam install $(find . -name '*.opam')` to ensure that any vendored projects are picked up (and their dependencies are installed), but this is still only really a heuristic.

**Comment by tomjridge** [comment]
I think this was my mistake - there was an old version of repr installed which somehow wasn't overridden by the pin perhaps? Anyway, things seem fine now. For reference, after a fresh checkout I do:

```
cd /tmp/l/github/irmin
git submodule update --init --recursive
opam install . --deps-only --with-test --with-doc # should pin the appropriate repos
dune build
dune runtest
```

Thanks both for your help.

**Comment by tomjridge** [comment]
Issue resolved.
