### ISSUE TITLE
irmin: add lock files

### ISSUE THREAD

**Issue by maiste** [mirage/irmin#1595]
To ensure users can create a switch without error, couldn't we add `x.opam.locked` files into the repository?
Thanks to this, users could simply build a switch with:
```sh
 $ opam switch create . --deps-only --locked
```
The drawback is that when we release a new version, we must update these files.

**Comment by samoht** [comment]
Adding a lock file is a good idea but I would rather recommend users to do `opam monorepo pull` instead of an `opam switch create` in that case.

**Comment by maiste** [comment]
As I'm not a user of __opam monorepo__: what is the difference between `opam switch create` and `opam monorepo pull`? 

Also, in this case, should the lock files be created with `opam monorepo lock`?

**Comment by CraigFe** [comment]
[`opam monorepo`](https://github.com/ocamllabs/opam-monorepo) is a plugin to Opam that automates vendoring of Dune projects in a subdirectory in the project tree, so `opam monorepo lock` also runs a solver and writes a lock file containing the computed fixed versions, but that lock file _also_ contains the development Git repositories so that the projects can be `git clone`-ed. Then `opam monorepo pull` fetches the dependencies locally so that `dune build` Just Works™ and there's no need to invoke `opam` to compile things.

AFAIK, the lock file produced by `opam monorepo lock` is fully-compatible with `opam switch create` (but the converse is not true).

**Comment by samoht** [comment]
It's still a good idea to install a lock file for anyone who wants to compile the irmin binary easily.

**Comment by maiste** [comment]
The lock file doesn't seem to be necessary as it has been moved to https://github.com/tarides/irmin-scratch.
Closing it. Feel free to reopen if needed.
