### ISSUE TITLE
upgrade from 2.x to 3.y

### ISSUE THREAD

**Issue by hannesm** [mirage/irmin#1813]
Hello,

when attempting to upgrade from Irmin 2.10 to 3.x, I encounter some issues. The following code:

```OCaml
module Store = Irmin_mirage_git.Mem.KV(Irmin.Contents.String)
```

results now in an error:
```shell
Error: The functor application is ill-typed.
       These arguments:
         Irmin.Contents.String
       do not match these parameters:
         functor  -> ...
       The following extra argument is provided
           Irmin.Contents.String :
           sig
             type t = string
             val t : t Irmin__.Type.t
             val merge : t option Irmin__.Merge.t
           end
```

Is using `Irmin_mirage_it.Mem.KV.Make(Irmin.Contents.String)`, I end up with an issue in (`module Sync = Irmin.Sync(Store)`), removing the functor argument, I no longer get a `pull` function - where is it (it used to be `Sync.pull`)?

Also,
```OCaml
        let ptime =
          match Ptime.of_float_s (Int64.to_float (Irmin.Info.date info)) with
          | None -> Ptime.v (P.now_d_ps ())
          | Some d -> d
        in
```

no longer works, since `Irmin.Info.date` is not bound anymore.

Are these breaking changes expected? I couldn't find documentation about how to migrate? Is there any incentive to upgrade to irmin 3.y?

**Comment by zshipko** [comment]
Yes, these are expected changes but we should definitely have better documentation available for helping people upgrade. (I will start a document to help list these things out)

Similar to how you needed to use the `Make` in `KV`, there is now `Irmin.Sync.Make` which does what you're trying to accomplish:

```ocaml
module Store = Irmin_mirage_git.Mem.KV.Make(Irmin.Contents.String)
module Sync = Irmin.Sync.Make(Store)
```

As far as I know these `Make` functors have been added to try to provide a more uniform naming scheme for functors across the Irmin codebase.

`Info` has been moved into `Store` to allow custom definitions. Instead of `Irmin.Info`, use `Store.Info`:
```ocaml
    let ptime =
          match Ptime.of_float_s (Int64.to_float (Store.Info.date info)) with
          | None -> Ptime.v (P.now_d_ps ())
          | Some d -> d
        in
```

If you run into anything else I'm happy to help get it working

**Comment by hannesm** [comment]
Thanks for your reply, I'm no longer using irmin, so closing this issue.
