### ISSUE TITLE
irmin-pack: assertion failure when calling `flush` for a read-only index

### ISSUE THREAD

**Issue by metanivek** [mirage/irmin#2043]
Currently, we `assert false` if we call `flush` for a read-only index. See https://gitlab.com/tezos/tezos/-/issues/3520 for more context.

Is it the best solution to `assert false` in this situation? 

Reasons I see for either making this a no-op or returning an `Error`:

- Yes this is a usage error but throwing an exception (and likely crashing the process) because of this seems more than is necessary since it does not harm the system if we ignore these calls
- The current api uses an error monad but we raise an exception; that is a break in expectation

**Comment by zshipko** [comment]
I’m on the fence about making it a noop because even though it is harmless to ignore it might indicate some kind of API usage issue if flush is being called on a readonly store. It seems like an error might help them identify the issue and fix it?

I don’t have strong feelings either way though.

**Comment by metanivek** [comment]
Yeah, it's definitely in the category of incorrect API usage. I lean slightly towards returning an `Error` instead of throwing an exception since it makes the error explicit for in calling code (like you're saying) and coheres with the current API. 

The downside of an `Error` is it is awkward ergonomics if you know you've created a read-write instance. The ideal from an ergonomics perspective would be to not let this function be called at all with read-only instances through changes to `t` (perhaps using https://github.com/mirage/irmin/blob/main/src/irmin/perms.ml), but that is definitely a more involved change.

**Comment by zshipko** [comment]
Agreed, something at the type level would be ideal!

It's not such a big issue because if you are knowingly calling `flush` on a readonly store then you're free to ignore the error result.

It looks like `close`, `reload` and `flush` all `assert false` when the instance is readonly, we should definitely make sure that they all handle it the same. I can make a PR to have them return ```Error `Ro_not_allowed``` instead of `assert false` if we agree that is the best fix.
