### ISSUE TITLE
Where are gone all docs ? 

### ISSUE THREAD

**Issue by benjaminVadon** [mirage/irmin#414]
I there.
Before, there was a documentation about API, and also Http  API.
It was very useful. 
Do you plan to rollback them ? Also, are  they still valid ?

**Comment by samoht** [comment]
Hi! I removed the wiki docs because they were getting outdated very quickly. I am planning to complete the online API doc with more example of uses, so it should be self-describing and complete.

Regarding the HTTP doc. I have removed the high-level bindings (because it was not clear to me if people were using it, and it was quite a complex piece and updating it to webmachine would have been a bit too painful), but if you are using it I can try to write a new/simple HTTP backend if that something that you are depending on.

**Comment by benjaminVadon** [comment]
Yes, I saw that reading others closed issues and last commits. It's why I closed this issue.
Yes, I'm using HTTP high-level bindings because it's the easiest way to use irmin with other programs not written in Ocaml, in my case a nodejs one. JsOfOcaml version was not adapted with my current knowledge.
If you think you have some time to build a simple HTTP backend ,with read/write basics, I may contribute to it after (get history, branches, ...)
Do you want a new issue for this ?

**Comment by samoht** [comment]
> Do you want a new issue for this ?

Yes please!

**Comment by benjaminVadon** [comment]
That's done here : #415
