### ISSUE TITLE
export/import

### ISSUE THREAD

**Issue by nickbetteridge** [mirage/irmin#455]
I can create a store, read/write/list etc, without any problems. Both the AO and RW data in the repo are observable (ie in RW I can see a 'master' key/value and in the AO there are lots of hashes/"{node...} etc).
When I export, create a new db/repo and then import, the AO data is imported perfectly, but RW is completely empty - unable to list the keys. Any hints on the step I've missed out?
```
    let config = Idb.config db_name in
    let db_info fmt = info "Nick" fmt in
    I.Repo.v config >>= fun repo ->
    I.master repo >>= fun store ->
    print "Setting value 'alpha' to 'beta'";
    I.set store ~info:(db_info "Setting value 'alpha' to 'beta'") ["alpha"] "beta" >>= fun () ->
    print "Setting value 'white' to 'knight'";
    I.set ~info:(db_info "Setting value 'white' to 'knight'") store ["white"] "knight" >>= fun () ->
    print "Printing keys";
    List.iter (fun (step,tipe) ->
      print (" - "^step)
    ) keys;

    print "Exporting slice ...";
    I.Repo.export repo >>= fun slice ->

    let import_config = Idb.config import_db_name in
    let import_info fmt = info "Nick import" fmt in
    I.Repo.v import_config >>= fun import_repo ->
    I.master import_repo >>= fun import_store ->
    I.Repo.import import_repo slice >>*= fun () ->

    print "Checking import worked...";
    I.list import_store [] >>= fun keys ->
    print "Printing import keys";
    List.iter (fun (step,tipe) ->
      print (" - "^step)
    ) keys;
```

**Comment by samoht** [comment]
Thanks for the report, you are right: branches are not imported in the RW store as they are not part of the exported [slice](https://github.com/mirage/irmin/blob/master/src/irmin/slice.ml#L28-L32). The initial rational was that you didn't want to inadvertently modify your local branches because of an import (previous version of Irmin were doing this -- this was very confusing). 

The usual use-case is to also pass the references you are interested in around as well (usually only head) and then set them manually after the import. I agree this is not very nice, the import function should probably have some optional arguments to control this (Git would prefix all the branch name with the name of the remote to avoid overwrites -- maybe we can do something similar here with a `prefix` option).

Patches are welcome :-)

**Comment by nickbetteridge** [comment]
Thanks - used Head.find - I'll look into ```prefix``` - added to the todo list :-)
