### ISSUE TITLE
Support 32 bits

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#465]
See https://github.com/mirage/mirage-www/pull/562#issuecomment-316991562

It seems that the recent commits to speed-up hashing broke 32 bits support. We should test this (and fix the issue, probably by removing support for `int` in `Irmin.Type`)

**Comment by samoht** [comment]
@hannesm why do you think these 2 lines might break something? It seems to me that we always try to serialise to 64b, whatever the platform is, which is the right way to have a portable binary serialization. WDYT?

**Comment by hannesm** [comment]
I said `might` in another thread since `Int64.to_int` (actually done in https://github.com/mirage/irmin/pull/458/files#diff-0b43dc6466ffe5ba4e4629f71c33631eR898) sounds very unsafe to me.  I don't have sufficient insight into the code base to analyse whether there is an actual problem.  Also I'm not sure when this code is executed, and with what input (controlled by whom?), and whether the goals include dumping on 64bit and restoring on 32bit.

On 64bit, the Int64.to_int is also "unsafe": `Int64.to_int Int64.max_int -> -1`

**Comment by samoht** [comment]
See https://github.com/mirage/irmin/pull/469
