### ISSUE TITLE
Newbie issues

### ISSUE THREAD

**Issue by ansiwen** [mirage/irmin#479]
Irmin is for me - especially as a ocaml newcomer with limited functional programming experience - very challenging to get started with. Lot's of things that might be obvious to the seasoned ocaml coder are not mentioned, there is very limited example code, and it's difficult to get an overview of how all the modules depend on each other, especially because of the extensive use of higher order functors. I will collect here all the things that I struggled with during getting started with Irmin to help improve the experience for other newcomers in the future.

- Which backends actually work in a MirageOS unikernel, and which depend on Unix modules.
- How do all the modules fit together? There is Irmin_unix.Git.FS and Irmin_unix.Git.Mem, but also Irmin_fs and Irmin_git.FS and Irmin_git.Mem? What are the differences? How to combine all these? 
- Git: there is the Git file structure and the Git protocol. The file structure can be used as a storage backend, if there is a file system available (Unix), but what about the git protocol? Is it usable as a backend (set/read) or only as a way to sync one repo to another (push/pull)?
- How to define your own content type? The content type must provide a Irmin.Type value, but what is that, why is it necessary, what is it used for? What to do with the pp and of_string functions, if the content type is binary, like a JPG image, and again, when exactly are they used?
- Why is it called Irmin_mem.KV although it seems to be a KV_MAKER functor that _produces_ a KV?
- ... (more to come)

**Comment by dinosaure** [comment]
On the `ocaml-git` side, I can clarify some points - but keep in your mind, `ocaml-git` is one back-end of Irmin (not the only one).

* `ocaml-git` works on MirageOS ans Unix back-end
* `Irmin_git.*` is an application of Irmin on the Git back-end. However, a Git back-end does not mean anything yet. In fact, `ocaml-git` ;need a back-end too ... `ocaml-git` could use a *unix* back-end (Unix I/O operations) and your *unix* file-system to store objects (like `Irmin_unix.Git.FS`) _or_ a *unix* back-end with a memory (which stores your objects) (like `Irmin_unix.Git.Mem`)

About the point below, it's a contraint from the MirageOS. Indeed, we can use the MirageOS I/O operations, however we store Git objects on the memory (obviously because on a MirageOS, it could not be mandatory to have a *file-system*). So, it could be: `Irmin_mirage.Git.Mem`.

* Currently, on `ocaml-git`, you can pull/fetch/clone (independently from which back-end your use). But, I worked on a [PR](https://github.com/mirage/ocaml-git/pull/227) which it's possible to push. About set/read, these operations are available independently the back-end too (because it's a part of the core).

For example, in the memory back-end, we use an hashtbl to set and read reference and store inside others Git objects. For a file-system back-end (Unix or MirageOS), we use the same structure than Git (see `.git`).

@samoht loves secretly functors

It seems to be complex, and yes it's complex but the result key about that is to have a full abstraction of the KV-store - and can I have a multiple representation of the same KV-Store.

**Comment by samoht** [comment]
@marcoonroad since the beginning of 2018 we have set-up a [new company](http://tarides.com) to help with the maintenance and development of Irmin (and MirageOS). I am currently working to gather some fundings and once this is a bit stabilised we have plans to write new tutorials and to refresh the external API (new CLI, refreshed language bindings, cap'n'proto and graphQL endpoints, ...) in the coming months. Hopefully I can update you with something more concrete pretty soon.

**Comment by samoht** [comment]
In case you missed it, a preview of the tutorials is available here: https://zshipko.github.io/irmin-tutorial

I am closing this issue now, but if you still have questions feel free to new issues.
