### ISSUE TITLE
Irmin.Type.decode_json returns error on some character values

### ISSUE THREAD

**Issue by gowthamk** [mirage/irmin#631]
Maybe a problem with jsonm, but here it goes:

```
open Lwt.Infix
open Irmin_unix
open Printf

type t = {x: char}

let t =
  let open Irmin.Type in
  record "point" (fun x -> {x})
  |+ field "x" char (fun p -> p.x)
  |> sealr


let pp_json = Irmin.Type.pp_json ~minify:false t

let () =
  let p = {x=Char.chr 174;} in
  let s = Fmt.strf "%a\n" pp_json p in
  let _ = printf "%s\n" s in
  let decoder = Jsonm.decoder (`String s) in
  let res = Irmin.Type.decode_json t decoder in
  match res with
    | Ok _ -> printf "Result Ok\n"
    | Error (`Msg s) -> printf "Result Error: %s\n" s
````

And here is a sample run:

```
$ocamlfind ocamlopt test3.ml -o test3 -package ezjsonm,irmin-unix,lwt.unix -linkpkg -thread                                                   
$./test3                                         
{                                             
  "x": ""                                     
}                                             

Result Error: illegal bytes in character stream (AE)
```

The error doesn't occur for all character values, for e.g., `Char.chr 111` works fine. 

Irmin packages are pinned to 1.4 branch (plus commit [57c74cb](https://github.com/zshipko/irmin/commit/57c74cbbeeb836af802045e45de41d51da9aa341)).

**Comment by zshipko** [comment]
This seems to be due to the way that `jsonm` encodes characters larger than `127`.

```ocaml
utop # Ezjsonm.encode_string "\126";;
- : Ezjsonm.value = `String "~"
```
versus

```ocaml
utop # Ezjsonm.encode_string "\128";;
- : Ezjsonm.value = `O [("hex", `String "80")]
```
I will have to add this case to the Irmin json decoder.

**Comment by gowthamk** [comment]
Thanks, @zshipko!

**Comment by zshipko** [comment]
Sorry @gowthamk, it's actually more complicated than I thought. The `ezjsonm` example above is not the default behavior of `jsonm`, it looks like `jsonm` considers characters outside of 0-127 invalid:

```ocaml
Jsonm.decode (Jsonm.decoder (`String "\128"));;
- : [> `Await | `End | `Error of Jsonm.error | `Lexeme of Jsonm.lexeme ] =
`Error (`Illegal_bytes "")
```

To make the original example work, we can either mimic the way `ezjsonm` handles it using a hex-object or consider this an error. 

@samoht, what do you think? It seems like using hex-object is not that nice, since it might lead to unexpected cases on the user's end. It might be best to just suggest using an `int` rather than `char` in these cases?

**Comment by zshipko** [comment]
@samoht, this also seems to affect JSON strings with weird characters in them:

```ocaml
utop # Irmin.Type.of_json_string Irmin.Type.string "\"\128\129aaa\"";;
- : (string, [ `Msg of string ]) result =
Error (`Msg "illegal bytes in character stream (80)")
```
that means we should probably figure out a better solution than just adding documentation after all...

One possibility would be to port all the JSON parsing/encoding to use `yojson`, since it is now a dependency for `irmin-graphql` -- that way we would also avoid depending on two different JSON libraries. From a simple test (similar to the one above), `yojson` seems to handle that input in the way that we want it to.

**Comment by samoht** [comment]
How does Yojson handle that case? Trying to embed a non UTF8 string in a JSON string is probably not a good idea. Is there a good way to escape these?

**Comment by zshipko** [comment]
Yojson leaves the invalid characters, which is what I would expect the behavior to be. However, I also agree that it's not a good idea to pass around non UTF-8 strings using JSON. 

Figuring out a good way of escaping these characters seems ideal. The only way I can think of is by using base64 when encoding string values that contain invalid characters, but that complicates encoding/decoding a bit.

**Comment by samoht** [comment]
This is similar to what is done in ezjsonm: https://github.com/mirage/ezjsonm/blob/master/lib/ezjsonm.ml#L266-L271

I think I reverted this because it was a bit slow to scan the full string on every encode, but I guess that's the only and right way to do this. Would you mind adding something similar in `Irmin.Type`?

**Comment by zshipko** [comment]
Yeah, sure. I will also do something like that for the `char` type while I'm at it.
