### ISSUE TITLE
Advice Using Irmin

### ISSUE THREAD

**Issue by jordwalke** [mirage/irmin#679]
I have a few questions about using Irmin:

- Do you want people to use Irmin in general (do you think it's ready for public consumption)?
- For new projects, do you recommend trying Irmin (1.4) or using the unreleased 2.0 (from Github)? I see that releasing 2.0 is pretty close around the corner, and I'm wondering if new projects should just link to 2.0 in anticipation and to report bugs.
- If users have questions about using Irmin, do you prefer Github Issues as a way to ask questions?
- Is there a community of open source Irmin users who collaborate to support newcomers, share examples/tools/suggestions?

**Comment by avsm** [comment]
Thanks for the enquiries!

> Do you want people to use Irmin in general (do you think it's ready for public consumption)?

This is a a very broad question.  Irmin is already used in production by several projects (https://github.com/moby/datakit, https://gitlab.com/tezos/tezos among others), so it's already being used in public consumption.  It would be far easier to answer if you could highlight the domain in which you intend to operate so that we can give a more specific answer.

> For new projects, do you recommend trying Irmin (1.4) or using the unreleased 2.0 (from Github)? I see that releasing 2.0 is pretty close around the corner, and I'm wondering if new projects should just link to 2.0 in anticipation and to report bugs.

Using Irmin 2.0 is recommended (#658) -- there has been a very large behind the scenes overhaul, and bugfixes in associated libraries (such as ocaml-git).  The 1.0 trees will of course continue to work for existing projects, but new projects would benefit from the performance improvements in the dev version.

> If users have questions about using Irmin, do you prefer Github Issues as a way to ask questions?

If by 'user' you mean a developer linking against the Irmin codebase (as opposed to using a product that embeds Irmin), then a GitHub issue would be fine.  Even better are questions combined with followup PRs to improve the documentation once you get your answer ;-)

> Is there a community of open source Irmin users who collaborate to support newcomers, share examples/tools/suggestions?

Irmin is a [MirageOS](https://mirage.io) project, so the usual rules for interaction with any MirageOS libraries apply.  We primarily use GitHub for issues, [discuss.ocaml.org](https://discuss.ocaml.org) with the `mirageos` or `irmin` tags for threaded discussions, the <mirageos-devel@lists.xenproject.org> email list, and `#mirage` on IRC.   Please bear in mind that we're a small team, so issues are best raised with as much context and reproducibility as possible to make responses easier.

Hope to hear more about your usecases for Irmin in the future!  It would be good to close out this issue with clarifications summarised to the README of the Irmin project.

**Comment by samoht** [comment]
I'm closing the issue as @avsm replies seem to cover the initial questions. Please feel free to re-open / open more specific issues if you have further questions.

**Comment by Tails** [comment]
I was looking for GraphQL support (which is not in 1.4 if I'm not mistaken) and am trying to compile the current master (2.0?) "as recommended". Is that already possible or is the release waiting on an external dependency? 

``` Dockerfile
#Dockerfile
FROM ocaml/opam2:4.07

# system dependencies
RUN sudo apt-get update && \
    sudo apt-get install -y \
      libgmp-dev \
      m4 \
      ocaml-nox \
      autoconf \
      pkg-config

# opam doesnt install globally it seems
ENV PATH="/home/opam/.opam/4.07/bin/irmin:${PATH}"

# install irmin packages (TODO: wait for release)
# RUN opam install irmin-unix

# Irmin OCaml dependencies
RUN opam install \
            dune \
            git \
            mirage-clock-lwt \
            graphql-lwt \
            cohttp-lwt \
            graphql-cohttp \
            webmachine \
            git-mirage \
            mtime \
            git-unix \
            alcotest \
            irmin-watcher \
            yaml && \
    sudo ln -s /home/opam/.opam/4.07/bin/dune /usr/bin/dune

# clone from a commit that is reported as being able to build successfully
RUN (git clone https://github.com/mirage/irmin.git irmin \
      && cd irmin && \
      git checkout 3db4c59cf6a2b8e41cdbf3448c05e3f1c4f4dfea)

# attempt build (fails)
RUN cd irmin && \
    opam switch 4.07 && \
    eval $(opam env) && \
    dune build

# # define runtime dir
# RUN sudo mkdir /store
# WORKDIR /store
#
# # add configuration file for global irmin CLI command
# ADD data/irmin.yml irmin.yml
#
# VOLUME /store
#
# # port for graphql server
# EXPOSE 8080

# # according to https://zshipko.github.io/irmin-tutorial/UsingTheCommandLine.html
# ENTRYPOINT irmin graphql --port 8080
```

**Comment by samoht** [comment]
The current master relies only on the development versions of `git` and `git-http` (they should be released soon, /cc @dinosaure).

If you use opam2, that means:
```
$ cd <path/to/irmin/sources>
$ opam pin add git --dev -n
$ opam pin add git-http --dev -n
$ opam install . --deps
$ dune exec -- irmin graphql --port 8080
```

**Comment by Tails** [comment]
> The current master relies only on the development versions of `git` and `git-http` (they should be released soon, /cc @dinosaure).
> 
> If you use opam2, that means:
> 
> ```
> $ cd <path/to/irmin/sources>
> $ opam pin add git --dev -n
> $ opam pin add git-http --dev -n
> $ opam install . --deps
> $ dune exec -- irmin graphql --port 8080
> ```

Thank you for your quick reply! It took me a while to get it working. For reference, this is what worked:

```Dockerfile
#Dockerfile
FROM ocaml/opam2:4.07

# system dependencies
RUN sudo apt-get update && \
    sudo apt-get install -y \
      libgmp-dev \
      m4 \
      ocaml-nox \
      autoconf \
      pkg-config

# Irmin OCaml dependencies
RUN opam update && \
    opam install dune && \
    sudo ln -s /home/opam/.opam/4.07/bin/dune /usr/bin/dune

WORKDIR /home/opam

# I needed to manually add the following packages since they could not be found through opam.
# manually download these and unpack in the context dir

# https://github.com/mirage/digestif/releases/download/v0.7.2/digestif-v0.7.2.tbz
COPY ./digestif-v0.7.2/ ./digestif-v0.7.2/

# https://github.com/dinosaure/checkseum/releases/download/v0.1.0/checkseum-v0.1.0.tbz
COPY ./checkseum-v0.1.0/ ./checkseum-v0.1.0/

# clone from a commit that is reported as being able to build successfully
RUN git clone https://github.com/mirage/irmin.git irmin

# build irmin using the dev version of Git and two of its unresolved dependencies
RUN cd irmin && \
    opam switch 4.07 && \
    eval $(opam env) && \
    opam pin add git --dev -n && \
    opam pin add git-http --dev -n && \
    opam pin digestif ../digestif-v0.7.2 && \
    opam pin checkseum ../checkseum-v0.1.0/ && \
    opam install . --deps && \
    dune build && \
    dune install

RUN sudo mkdir /store
WORKDIR /store
VOLUME /store

COPY ./entrypoint.sh /entrypoint.sh
RUN sudo chmod +x /entrypoint.sh

# port for graphql server
EXPOSE 8080

# # according to https://zshipko.github.io/irmin-tutorial/UsingTheCommandLine.html
# ENTRYPOINT irmin graphql --port 8080
CMD eval $(opam env) && \
    irmin init -v && \
    irmin graphql -v --port 8080

```

**Comment by avsm** [comment]
@dinosaure @samoht we could now use opam2's `pin-depends` field to let a direct `opam install .` work with Irmin, even ahead of the git release.

**Comment by samoht** [comment]
Now that `pin-depends` have been merged (see https://github.com/mirage/irmin/pull/707), installation is a matter of:

```
opam install --deps .
make
```
