### ISSUE TITLE
Predictable Caching

### ISSUE THREAD

**Issue by Galfour** [mirage/irmin#929]
> I imagine there are caching strategies implemented in Irmin. But I can't find anything Googling this.
Where can I read more about it? Is it exposed to the users in some way? (Like, is it possible to disable it?)

> caches are handled via https://mirage.github.io/irmin/irmin/Irmin/module-type-S/Tree/index.html You can clear tree caches by using Tree.clear (https://mirage.github.io/irmin/irmin/Irmin/module-type-S/Tree/index.html#caches) -- you can use it to clear the cache after every operation. Caches for content-adressable stores are tricky to get right (and you need them if you don't want your operations to be awfully slow). Happy to discuss further/improve that API via the irmin's Github issue tracker if you'd like.

In the context of blockchains, predictable access times (and thus predictable caching) and fast access times are comparably important.

The main reason is that blockchains have a rough computational model of user provided operations, in the form of [gas](https://www.investopedia.com/terms/g/gas-ethereum.asp). Mis-priced operations in terms of gas (as in, operations which gas cost don't reflect the actual underlying cost) could lead to DOS attacks. The typical way to do so would be to create a block that contains operations that are much more computationally expensive than expected, thus halting miners/bakers.

If everything fits in the cache right now, then it is not an immediate problem. But that won't scale as the state grows bigger, So I'm looking for ways to model this explicitly, and for an API that supports this.

**Comment by samoht** [comment]
I think it's relatively easy to give an upper bound complexity for some of the operations -- the model is the same as purely functional n-ary trees (for tezos [for reads n=32](https://gitlab.com/tezos/tezos/blob/master/src/lib_storage/context.ml#L210) and [for writes n=256](https://gitlab.com/tezos/tezos/blob/master/src/lib_storage/context.ml#L212)) (if you assume a cache miss for every request for sub-trees). 

The behaviour is a bit complex for operations when the tree width is between 32 and 256, as `irmin-pack` is adding additional (i-)nodes to make sure no tree nodes on disk have a bounded size (which improves many things, like a global space reduction due to better de-duplication).

Happy to add any API which will help you define a right model for this. For instance, we could certainly add a mode where we never cache anything (that'll just be ... very ... very ... slow) and expose a few metrics (like number or total reads and writes to disk) so you can test that your models are correct. Or something else if you have a better idea :-)

**Comment by Galfour** [comment]
> For instance, we could certainly add a mode where we never cache anything (that'll just be ... very ... very ... slow) and expose a few metrics (like number or total reads and writes to disk) so you can test that your models are correct.

That would be perfect. That way, I could start with some macro-benches to at least get a better feel for all of this and some starting numbers.

**Comment by samoht** [comment]
Most of the functions in `Tree` now takes a `cache` argument to control caching since irmin 2.8.
